language: python
python:
  - "3.7"
install:
  - pip install -r requirements.txt
deploy:
  provider: heroku
  api_key: 1fc1ccfa-517c-4a9e-8d36-695216adfabd
  app: testflaskapp-123
  run: "python app.py"


script:
  - python app.py &
  - sleep 5
  - python app_test.py
